const GalleryArray = [
  {
    title: "Splendid Fairy Wren",
    id: 1,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/splnd%20wren.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Sun Parakeet",
    id: 2,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/sun%20parakeet.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Red-rumped Parakeet",
    id: 3,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/redrumpd.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Cannon Ball Flowers",
    id: 4,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/cannonballflwrs.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Acaia Tree",
    id: 5,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/acaia%20tree.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Celestial Gate",
    id: 7,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/celestial%20gate.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Cherry Blossoms",
    id: 9,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/cherry%20blossoms.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Palm Tree Beach",
    id: 8,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/beach.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Fairy Gate",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/fairy%20gate.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Blue Macaw",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/blue%20macaw.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Owl on Cherry Tree",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/owl.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Luna Moth",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/luna%20moth.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "King Fisher",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/king%20fisher.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Joy Comes in the Morning",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/joy.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
  {
    title: "Magnolias",
    id: 6,
    category: ["bird"],
    products: ["Canvas Print"],
    images: "https://serenityimages.studio/images/art/magnolias.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
];

export default GalleryArray;
// module.exports = {
//   GalleryArray,
// };
