const GalleryArray = [
  {
    title: "Splendid Fairy Wren",
    id: 1,
    category: ["bird", "birds", "sky", "sunset", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/splnd%20wren.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Sun Parakeet",
    id: 2,
    category: ["birds", "bird", "flowers", "flower", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/sun%20parakeet.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Red-rumped Parakeet",
    id: 3,
    category: ["birds", "bird", "sunset", "sky", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/redrumpd.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Cannon Ball Flowers",
    id: 4,
    category: ["flowers", "flower", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/cannonballflwrs.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Acaia Tree",
    id: 5,
    category: ["landscape", "tree", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/acaia%20tree.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Celestial Gate",
    id: 7,
    category: [
      "fantasy",
      "landscape",
      "sunset",
      "night",
      "ocean",
      "gate",
      "gates",
      "tori",
      "",
    ],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/celestial%20gate.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 11x14 inch wrapped canvas.",
    price: 70,
  },
  {
    title: "Cherry Blossoms",
    id: 9,
    category: ["flowers", "sky", "flower", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/cherry%20blossoms.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch wrapped canvas.",
    price: 50,
  },
  {
    title: "Palm Tree Beach",
    id: 8,
    category: ["ocean", "beach", "seascape", "palmtree", "palm tree", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/beach.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 16x20 inch wrapped canvas.",
    price: 200,
  },
  {
    title: "Fairy Gate",
    id: 6,
    category: ["fantasy", "landscape", "night", "sunset", "tree", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/fairy%20gate.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Blue Macaw",
    id: 10,
    category: ["birds", "bird", "night", "macaw", "bird", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/blue%20macaw.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Owl on Cherry Tree",
    id: 11,
    category: [
      "birds",
      "bird",
      "flowers",
      "flower",
      "night",
      "owl",
      "cherry",
      "blossom",
      "blossoms",
      "",
    ],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/owl.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "Luna Moth",
    id: 12,
    category: ["moths", "moth", "night", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/luna%20moth.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
  },
  {
    title: "King Fisher",
    id: 13,
    category: ["birds", "bird", "flowers", "flower", "sunset", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/king%20fisher.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 11x14 inch wrapped canvas.",
    price: 70,
  },
  {
    title: "Joy Comes in the Morning",
    id: 14,
    category: [
      "sunset",
      "butterfly",
      "monarch",
      "butterfly",
      "butterflies",
      "",
    ],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/joy.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 16x20 inch wrapped canvas.",
    price: 200,
  },
  {
    title: "Magnolias",
    id: 15,
    category: ["flowers", "flower", ""],
    products: ["Canvas Print"],
    baseImage:
      "https://user-interface-ii-5fl9n5s96.vercel.app/images/art/magnolias.jpg",
    sizes: ["small"],
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 21,
  },
];

export default GalleryArray;
