import sunPB from "../images/galleryPics/bigger/sun-parakeet-mimosa-flowers-canvas.webp";
import cannonballflwrsB from "../images/galleryPics/bigger/cannonball-flowers-canvas.webp";
import celestialB from "../images/galleryPics/bigger/celestial-gate-b.jpg";
import cherryB from "../images/galleryPics/bigger/cherry-blossom-branch1273986-canvas.webp";
import fairyGateB from "../images/galleryPics/bigger/fairy-gate2730911-canvas.webp";
import blueMB from "../images/galleryPics/bigger/dawn-bringer-canvas.webp";
import magsB from "../images/galleryPics/bigger/magnolia2832489-canvas.webp";
import nightOwlB from "../images/galleryPics/bigger/night-owl2246387-canvas.webp";
import kingFB from "../images/galleryPics/bigger/kingfisher-sunset2724780-canvas.webp";
import lunaMB from "../images/galleryPics/bigger/luna-moth2882386-canvas.webp";
import acaiaB from "../images/galleryPics/bigger/acaia-tree-canvas.webp";
import amParrB from "../images/galleryPics/bigger/parrots-of-the-amazon1436762-canvas.webp";
import blueJayB from "../images/galleryPics/bigger/blue-jay-on-almond-blossom-tree-canvas.webp";
import calmB from "../images/galleryPics/bigger/calm-blue2679832-canvas.webp";
import cherry2B from "../images/galleryPics/bigger/cherry-blossoms1108697-canvas.webp";
import chickadeeB from "../images/galleryPics/bigger/chickadee-on-cherry-tree-canvas.webp";
import crWaveB from "../images/galleryPics/bigger/cresting-wave1201498-canvas.webp";
import deernightB from "../images/galleryPics/bigger/deer-at-night-canvas.webp";
import deRoseB from "../images/galleryPics/bigger/desert-rose1687521-canvas.webp";
import orangesB from "../images/galleryPics/bigger/flowing-orange-tree-canvas.webp";
import goldfishB from "../images/galleryPics/bigger/gold-fish1108676-canvas.webp";
import healed from "../images/galleryPics/healed-and-whole.jpg";
import healedB from "../images/galleryPics/bigger/healed-and-whole-canvas.webp";
import hidhum from "../images/galleryPics/hidden-humming-bird.jpg";
import hidhumB from "../images/galleryPics/bigger/hidden-humming-bird-canvas.webp";
import humbmrn from "../images/galleryPics/hummingBirdMorningGlorySunrise.jpg";
import humbmrnB from "../images/galleryPics/bigger/humming-bird-morning-glory-sunrise-canvas.webp";
import cranefuji from "../images/galleryPics/japanese-crane-over-mt-fuji.jpg";
import cranefujiB from "../images/galleryPics/bigger/japanese-crane-over-mt-fuji-canvas.webp";
import jellyf from "../images/galleryPics/jelly-fish.jpg";
import jellyfB from "../images/galleryPics/bigger/ac.webp";
import kngf from "../images/galleryPics/kingFisherB.webp";
import kngfB from "../images/galleryPics/bigger/king-fisher2064844-canvas.webp";
import bldngHrt from "../images/galleryPics/love-bleeds-bleeding-heart-canvas.webp";
import bldngHrtB from "../images/galleryPics/bigger/love-bleeds-bleeding-heart-canvas.webp";
import magSumm from "../images/galleryPics/magical-summer2631831-canvas.webp";
import magSummB from "../images/galleryPics/bigger/magical-summer2631831-canvas.webp";
import magJay from "../images/galleryPics/magpieJay.webp";
import magJayB from "../images/galleryPics/bigger/magpie-jay-canvas.webp";
import mercove from "../images/galleryPics/mermaid-cove1782029-canvas.webp";
import mercoveB from "../images/galleryPics/bigger/mermaid-cove1782029-canvas.webp";
import merRock from "../images/galleryPics/mermaidRock.webp";
import merRockB from "../images/galleryPics/bigger/mermaid-rock2625159-canvas.webp";
import monarch from "../images/galleryPics/monarch981986-canvas.webp";
import monarchB from "../images/galleryPics/bigger/monarch981986-canvas.webp";
import mnltRev from "../images/galleryPics/moonlitReverie.webp";
import mnltRevB from "../images/galleryPics/bigger/moonlit-reverie-canvas.webp";
import owlch from "../images/galleryPics/night-owl-on-blossoming-tree-canvas.webp";
import owlchB from "../images/galleryPics/bigger/night-owl-on-blossoming-tree-canvas.webp";
import nightHill from "../images/galleryPics/nightHill.webp";
import nightHillB from "../images/galleryPics/bigger/night-hill-canvas.webp";
import ocDrag from "../images/galleryPics/ocean-dragon-canvas.webp";
import ocDragB from "../images/galleryPics/bigger/ocean-dragon-canvas.webp";
import orioleLong from "../images/galleryPics/oriole-at-sunset-canvas.webp";
import orioleLongB from "../images/galleryPics/bigger/oriole-at-sunset-canvas.webp";
import pairMoths from "../images/galleryPics/pair-of-lunar-moths-canvas.webp";
import pairMothsB from "../images/galleryPics/bigger/pair-of-lunar-moths-canvas.webp";
import pFeathers from "../images/galleryPics/peacock-feather1608483-canvas.webp";
import pFeathersB from "../images/galleryPics/bigger/peacock-feather1608483-canvas.webp";
import pFlo from "../images/galleryPics/pink-flowers1145595-canvas.webp";
import pFloB from "../images/galleryPics/bigger/pink-flowers1145595-canvas.webp";
import simple from "../images/galleryPics/simpleThings.webp";
import simpleB from "../images/galleryPics/bigger/enjoy-the-simple-things1591696-canvas.webp";
import soli from "../images/galleryPics/solitary-beauty-canvas.webp";
import soliB from "../images/galleryPics/bigger/solitary-beauty-canvas.webp";
import sunDra from "../images/galleryPics/sunlight-dragon.jpg";
import sunDraB from "../images/galleryPics/bigger/sunlight-dragon1107358-canvas.webp";
import wingsNight from "../images/galleryPics/sunsetOwl.jpg";
import wingsNightB from "../images/galleryPics/bigger/sunset-owl1567202-canvas.webp";
import starFall from "../images/galleryPics/the-cosmos.jpg";
import starFallB from "../images/galleryPics/bigger/the-cosmos1196000-canvas.webp";
import morningGlory from "../images/galleryPics/the-glory-of-morning.jpg";
import morningGloryB from "../images/galleryPics/bigger/the-glory-of-morning1614410-canvas.webp";
import wren from "../images/galleryPics/the-wren.jpg";
import wrenB from "../images/galleryPics/bigger/the-wren975688-canvas.webp";
import thorns from "../images/galleryPics/thorns.jpg";
import thornsB from "../images/galleryPics/bigger/thorns1134445-canvas.webp";
import tsubaki from "../images/galleryPics/tsubaki.jpg";
import tsubakiB from "../images/galleryPics/bigger/tsubaki1258216-canvas.webp";
import winterEnd from "../images/galleryPics/wintersEnd.jpg";
import winterEndB from "../images/galleryPics/bigger/winters-end3829175-canvas.webp";
import nightFlightB from "../images/galleryPics/bigger/night-flight4477694-canvas.webp";
import bamboo from "../images/galleryPics/bamboo-forest4477598-canvas.webp";
import bambooB from "../images/galleryPics/bigger/bamboo-forest4477598-canvas.webp";
import jCranes from "../images/galleryPics/japanese-cranes4477782-canvas.webp";
import jCranesB from "../images/galleryPics/bigger/japanese-cranes4477782-canvas.webp";
import orioleOcean from "../images/galleryPics/oriole-over-the-ocean-canvas.webp";
import orioleOceanB from "../images/galleryPics/bigger/oriole-over-the-ocean-canvas.webp";
import owlLight from "../images/galleryPics/owl4477653-canvas.webp";
import owlLightB from "../images/galleryPics/bigger/owl4477653-canvas.webp";
import owlC from "../images/galleryPics/owl4478333-canvas.webp";
import owlCB from "../images/galleryPics/bigger/owl4478333-canvas.webp";
import whale from "../images/galleryPics/whale4478346-canvas.webp";
import whaleB from "../images/galleryPics/bigger/whale4478346-canvas.webp";
import loved from "../images/galleryPics/loved4499238-canvas.webp";
import lovedB from "../images/galleryPics/bigger/loved4499238-canvas.webp";
import pelican from "../images/galleryPics/brown-pelican4805939-canvas.webp";
import pelicanB from "../images/galleryPics/bigger/brown-pelican4805939-canvas.webp";
import splendidWren from "../images/galleryPics/male-splendid-fairy-wren-early-sunset-canvas.webp";
import splendidWrenB from "../images/galleryPics/bigger/male-splendid-fairy-wren-early-sunset-canvas.webp";
import pairpeacocks from "../images/galleryPics/a-pair-of-peacocks-canvas.webp";
import pairpeacocksB from "../images/galleryPics/bigger/a-pair-of-peacocks-canvas.webp";
import island from "../images/galleryPics/birth-of-an-island-canvas.webp";
import islandB from "../images/galleryPics/bigger/birth-of-an-island-canvas.webp";
import blubutterfly from "../images/galleryPics/blue-butterfly1093023-canvas.webp";
import blubutterflyB from "../images/galleryPics/bigger/blue-butterfly1093023-canvas.webp";
import bluheron from "../images/galleryPics/blue-heron4477792-prints.webp";
import bluheronB from "../images/galleryPics/bigger/blue-heron4477792-prints.webp";
import brightab from "../images/galleryPics/bright-sunset1233521-canvas.webp";
import brightabB from "../images/galleryPics/bigger/bright-sunset1233521-canvas.webp";
import bubbling from "../images/galleryPics/bubbling-river1215587-canvas.webp";
import bubblingB from "../images/galleryPics/bigger/bubbling-river1215587-canvas.webp";
import giantturtle from "../images/galleryPics/giant-sea-turtle1332531-canvas.webp";
import giantturtleB from "../images/galleryPics/bigger/giant-sea-turtle1332531-canvas.webp";
import gladi from "../images/galleryPics/gladiolus1101060-canvas.webp";
import gladiB from "../images/galleryPics/bigger/gladiolus1101060-canvas.webp";
import lakeside from "../images/galleryPics/lake-side2681835-canvas.webp";
import lakesideB from "../images/galleryPics/bigger/lake-side2681835-canvas.webp";
import wisteria from "../images/galleryPics/wisteria981935-canvas.webp";
import wisteriaB from "../images/galleryPics/bigger/wisteria981935-canvas.webp";
import coswat from "../images/galleryPics/those-cosmos-waters-canvas.webp";
import coswatB from "../images/galleryPics/bigger/those-cosmos-waters-canvas.webp";
import tit from "../images/galleryPics/the-longtailed-bird-canvas.webp";
import titB from "../images/galleryPics/bigger/the-longtailed-bird-canvas.webp";
import texas from "../images/galleryPics/texas-sea-side-canvas.webp";
import texasB from "../images/galleryPics/bigger/texas-sea-side-canvas.webp";
import swallbutrfly from "../images/galleryPics/swalowtail-butterfy-on-purple-cone-flower-canvas.webp";
import swallbutrflyB from "../images/galleryPics/bigger/swalowtail-butterfy-on-purple-cone-flower-canvas.webp";
import sunsrose from "../images/galleryPics/sunset-roses1270384-canvas.webp";
import sunsroseB from "../images/galleryPics/bigger/sunset-roses1270384-canvas.webp";
import seaturtle from "../images/galleryPics/sea-turtle1101114-canvas.webp";
import seaturtleB from "../images/galleryPics/bigger/sea-turtle1101114-canvas.webp";
import scmacaw from "../images/galleryPics/scarlet-macaw4477750-prints.webp";
import scmacawB from "../images/galleryPics/bigger/scarlet-macaw4477750-prints.webp";
import spiper from "../images/galleryPics/sand-pipers-on-the-beach-canvas.webp";
import spiperB from "../images/galleryPics/bigger/sand-pipers-on-the-beach-canvas.webp";
import bluenebula from "../images/galleryPics/blue-nebula.jpg";
import bluenebulaB from "../images/galleryPics/bigger/blue-nebula1278108-canvas.webp";
import fantasytree from "../images/galleryPics/fantasy-tree4477878-prints.webp";
import fantasytreeB from "../images/galleryPics/bigger/fantasy-tree4477878-prints.webp";
import cardinal from "../images/galleryPics/cardial-on-dogwood-tree.jpg";
import cardinalB from "../images/galleryPics/bigger/cardial-on-dogwood-tree-canvas.webp";
import fireneb from "../images/galleryPics/fire-edge-nebula.jpg";
import firenebB from "../images/galleryPics/bigger/fire-edge-nebula-canvas.webp";
import giraffe from "../images/galleryPics/giraffe2132847-prints.webp";
import giraffeB from "../images/galleryPics/bigger/giraffe2132847-prints.webp";
import ger from "../images/galleryPics/geraniums.jpg";
import gerB from "../images/galleryPics/bigger/geraniums1100717-canvas.webp";
import bwpanda from "../images/galleryPics/giant-panda.jpg";
import bwpandaB from "../images/galleryPics/bigger/giant-panda1151785-canvas.webp";
import gblu from "../images/galleryPics/golden-blues.jpg";
import gbluB from "../images/galleryPics/bigger/golden-blues1207399-canvas.webp";
import morn from "../images/galleryPics/morning-glories1381607-prints.webp";
import mornB from "../images/galleryPics/bigger/morning-glories1381607-prints.webp";
import palmbeach from "../images/galleryPics/palm-tree-beach4471863-prints.webp";
import palmbeachB from "../images/galleryPics/bigger/palm-tree-beach4471863-prints.webp";
import snowowl from "../images/galleryPics/snow-owl-on-cherry-tree-canvas.webp";
import snowowlB from "../images/galleryPics/bigger/snow-owl-on-cherry-tree-canvas.webp";
import pinkaqua from "../images/galleryPics/pink-aqua1252973-canvas.webp";
import pinkaquaB from "../images/galleryPics/bigger/pink-aqua1252973-canvas.webp";
import seafoam from "../images/galleryPics/sea-foam1287839-canvas.webp";
import seafoamB from "../images/galleryPics/bigger/sea-foam1287839-canvas.webp";
import sunfire from "../images/galleryPics/sun-fire.jpg";
import sunfireB from "../images/galleryPics/bigger/sun-fire1250862-canvas.webp";
import solarflare from "../images/galleryPics/solar-flare1345853-canvas.webp";
import solarflareB from "../images/galleryPics/bigger/solar-flare1345853-canvas.webp";
import pflwr from "../images/galleryPics/pink-flowers2803848-canvas.webp";
import pflwrB from "../images/galleryPics/bigger/pink-flowers2803848-canvas.webp";
import plum from "../images/galleryPics/plumeria-tree1801808-canvas.webp";
import plumB from "../images/galleryPics/bigger/plumeria-tree1801808-canvas.webp";
import pur from "../images/galleryPics/purselane-canvas.webp";
import purB from "../images/galleryPics/bigger/purselane-canvas.webp";
import seat from "../images/galleryPics/sea-turtle1109065-canvas.webp";
import seatB from "../images/galleryPics/bigger/sea-turtle1109065-canvas.webp";
import stuff from "../images/galleryPics/the-stuff-of-life.jpg";
import stuffB from "../images/galleryPics/bigger/the-stuff-of-life-prints.webp";
import enchant from "../images/galleryPics/enchanted-spring.webp";
import enchantB from "../images/galleryPics/bigger/enchanted-spring.webp";
import rise from "../images/galleryPics/rise-and-shine1136625-canvas.webp";
import riseB from "../images/galleryPics/bigger/rise-and-shine1136625-canvas.webp";

const GalleryArray = [
  {
    title: "Sunset Ocean View",
    id: 84,
    keyword: "sunset ocean view tree landscape sea water",
    medium: "acrylic canvas.",
    size: "6x4 inches.",
    description: "Acrylic paint on wrapped canvas.",
    price: 40,
    buy: "Contact to purchase.",
    etsyListing: null,
    image:
      "https://ctl.s6img.com/society6/img/HDeUvQp37W1bL0Z3rxI_QdqbbzI/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/HDeUvQp37W1bL0Z3rxI_QdqbbzI/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/sunset-ocean-view4949541_stretched-canvas?sku=s6-19953070p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/eW0ktbyXNK0ubSJMDWXnwyJM9jc/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-prints.jpg",
    s6Print:
      "https://society6.com/product/sunset-ocean-view4949541_print?sku=s6-19953070p4a1v45",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/iXCGRmobwc8fiIjpuSFJu0Lq3ZE/w_700/framed-prints/10x12/conservation-walnut/~artwork/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/sunset-ocean-view4949541_framed-print?sku=s6-19953070p21a12v63a13v54",
    s6TapestryImg:
      "https://ctl.s6img.com/society6/img/7mS92Br6D6rU6hk1n9vU2qpgDoI/w_700/tapestries/standard/~artwork,fw_5525,fh_6500,fy_-874,iw_5525,ih_8248/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-tapestries.jpg",
    s6Tapestry:
      "https://society6.com/product/sunset-ocean-view4949541_tapestry?sku=s6-19953070p42a55v412",
    s6WallHanging:
      "https://society6.com/product/sunset-ocean-view4949541_wall-hanging?sku=s6-19953070p74a221v774",
    s6WallHangingImage:
      "https://ctl.s6img.com/society6/img/u2ru-gbiKxuzjd3dRQ_FSU7XdAY/w_700/wall-hangings/small/front/~artwork,fw_4058,fh_5678,fy_-190,iw_4058,ih_6058/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-wall-hangings.jpg",
    s6Poster:
      "https://society6.com/product/sunset-ocean-view4949541_poster?sku=s6-19953070p66a213v756",
    s6PosterImage:
      "https://ctl.s6img.com/society6/img/ZhNXMjDCzYzvDa3CuINKNs1BYMg/w_700/posters/top/~artwork,fw_2718,fh_3618,fy_-220,iw_2718,ih_4057/s6-original-art-uploads/society6/uploads/misc/7d535eeb0b2c447aadf3e39cf0b6a5e0/~~/sunset-ocean-view4949541-posters.jpg",
  },
  {
    title: "Splendid Fairy Wren",
    id: 2,
    keyword: "birds sky sunset splendid tree wren",
    medium: "acrylic canvas",
    size: "9x12 inches.",
    description: "Acrylic paint on canvas sheet.",
    price: 60,
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/993109978/splendid-fairy-wren-acrylic-painting?ref=shop_home_active_7&frs=1",
    image:
      "https://ctl.s6img.com/society6/img/hSz_XCshPKhkK9Lq5azZM_vh5pA/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/fdf8fef8df1448a0b71d48fd6f11574b/~~/sunset-fairy-wren-bird-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/hSz_XCshPKhkK9Lq5azZM_vh5pA/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/fdf8fef8df1448a0b71d48fd6f11574b/~~/sunset-fairy-wren-bird-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/sunset-fairy-wren-bird_stretched-canvas?sku=s6-11749657p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/njQ7rnSjB1l0bCKrWqy9NKLtw_Q/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/fdf8fef8df1448a0b71d48fd6f11574b/~~/sunset-fairy-wren-bird-prints.jpg",
    s6Print:
      "https://society6.com/product/sunset-fairy-wren-bird_print?sku=s6-11749657p4a1v45",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/hKAbmQF4zoAdrx7HEL6V8qHu1Do/w_700/framed-prints/10x12/conservation-walnut/~artwork/s6-original-art-uploads/society6/uploads/misc/fdf8fef8df1448a0b71d48fd6f11574b/~~/sunset-fairy-wren-bird-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/sunset-fairy-wren-bird_framed-print?sku=s6-11749657p21a12v63a13v54",
    s6TapestryImg:
      "https://ctl.s6img.com/society6/img/_pZlH28M5SWk9rUpB-ual5Eqt4c/w_700/tapestries/standard/~artwork,fw_6500,fh_5525,fx_-552,iw_7603,ih_5525/s6-original-art-uploads/society6/uploads/misc/fdf8fef8df1448a0b71d48fd6f11574b/~~/sunset-fairy-wren-bird-tapestries.jpg",
    s6Tapestry:
      "https://society6.com/product/sunset-fairy-wren-bird_tapestry?sku=s6-11749657p42a55v412",
    s6WallHanging: "",
    s6WallHangingImage: null,
    s6Poster: "",
    s6PosterImage: null,
  },
  {
    title: "Red-rumped Parakeet",
    id: 3,
    keyword: "birds sunset sky tree leaves red parakeet",
    medium: "acrylic canvas",
    size: "9x12 inches.",
    description: "Acrylic paint on canvas sheet.",
    price: 60,
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007144707/red-rumped-parakeet-acrylic-painting?ref=shop_home_active_1&frs=1",
    image:
      "https://ctl.s6img.com/society6/img/3CBk2XP3qfcVdOmJW26ZbO_Q-_M/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/6e47b06b32184832a224f02dbb433f88/~~/red-rumped-parrot-at-sunset-canvas.jpg",
    s6CanvasPrintImg: null,
    s6CanvasPrint: "",
    s6PrintImg: null,
    s6Print: "",
    s6FramedImg: null,
    s6Framed: "",
    s6TapestryImg: null,
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: null,
    s6Poster: "",
    s6PosterImage: null,
  },
  {
    title: "Moonlit Reverie",
    id: 37,
    keyword: "moonlight moon tree landscape seascape night stars ocean water",
    medium: "canvas acrylic",
    size: "4x6 inches.",
    description: "Acrylic paint on canvas.",
    price: 40,
    buy: "Contact to purchase.",
    etsyListing: null,
    image:
      "https://ctl.s6img.com/society6/img/E3uzv3GSk24WINuK6_SkojWlDKI/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/965880541a204a28bef41eaca91f6618/~~/moonlit-reverie-canvas.jpg",
    s6CanvasPrintImg: null,
    s6CanvasPrint: "",
    s6PrintImg: null,
    s6Print: "",
    s6FramedImg: null,
    s6Framed: "",
    s6TapestryImg: null,
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: null,
    s6Poster: "",
    s6PosterImage: null,
  },
  {
    title: "Wolf Moon",
    id: 55,
    keyword: "wolf moon hill night sky stars space",
    medium: "canvas acrylic",
    size: "4x4 inches.",
    description: "Acrylic paint on canvas.",
    price: 30,
    image:
      "https://ctl.s6img.com/society6/img/AnbWDJB1wIogzjOcSx5zvunfM7o/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/ae67ea50231e44e1b3aef1eacc3beef3/~~/wolf-moon2516241-canvas.jpg",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Contact to purchase.",
    etsyListing: null,
  },
  {
    title: "Sunset Tree",
    id: 56,
    keyword: "tree sunset sea ocean water",
    medium: "canvas acrylic",
    size: "4x6 inches.",
    description: "Acrylic paint on canvas.",
    price: 40,
    image:
      "https://ctl.s6img.com/society6/img/dEF90rTxqPU1wTRG9AB-PMgBozw/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/bae5b7f00098441c9f3a2cd750b917c7/~~/sunset-branches2895395-canvas.jpg",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Contact to purchase.",
    etsyListing: null,
  },
  {
    title: "Night Flight",
    id: 57,
    keyword: "night moon owls flight trees",
    medium: "canvas acrylic",
    size: "9x12 inches.",
    description: "Acrylic paint on canvas.",
    price: 60,
    image: nightFlightB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/993206864/night-flight-owls-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Bamboo Forest",
    id: 58,
    keyword: "giant panda bamboo sun yellow",
    medium: "canvas acrylic",
    size: "4x4 inches.",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bambooB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Contact to purchase.",
    etsyListing: null,
  },
  {
    title: "Japanese Cranes",
    id: 59,
    keyword: "japanese cranes sky sunrise sunset tree landscape birds",
    medium: "canvas acrylic",
    size: "16x20 inches.",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: jCranesB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Scarlet Macaw",
    id: 82,
    keyword: "scarlet macaw birds",
    medium: "canvas acrylic",
    size: "12x24 inches.",
    description: "Acrylic paint on canvas.",
    price: 100,
    image: scmacawB,
    s6CanvasShow: "no",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Oriole over the Ocean",
    id: 60,
    keyword: "oriole bird tree cherry blossoms flowers pink ocean sea water",
    medium: "canvas acrylic",
    size: "12x24 inches.",
    description: "Acrylic paint on canvas.",
    price: 100,
    image: orioleOceanB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Contact to purchase.",
    etsyListing: null,
  },
  {
    title: "Owl",
    id: 61,
    keyword: "owl bird moon sky night cherry blossoms flowers plumb tree",
    medium: "canvas acrylic",
    size: "4x6 inches.",
    description: "Acrylic paint on canvas.",
    price: 40,
    image: owlCB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Whale",
    id: 62,
    keyword: "whale sea ocean mini",
    medium: "canvas acrylic",
    size: "4x4 inches.",
    description: "Acrylic paint on canvas.",
    price: 30,
    buy: "Contact to purchase.",
    etsyListing: null,
    image:
      "https://ctl.s6img.com/society6/img/cSK6mmmwUJndGpdcftce-OBSqYA/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/cSK6mmmwUJndGpdcftce-OBSqYA/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/whale4478346_stretched-canvas?sku=s6-19143535p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/ZMF9FSxnQtGmnk8g5fJEhGfsuW4/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-prints.jpg",
    s6Print:
      "https://society6.com/product/whale4478346_print?sku=s6-19143535p4a1v45",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/JAC68vG8QOCMbTKJsfcvtIvIPT4/w_700/framed-prints/10x12/conservation-walnut/~artwork/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/whale4478346_framed-print?sku=s6-19143535p21a12v63a13v54",
    s6TapestryImg:
      "https://ctl.s6img.com/society6/img/cWvBZi-CSUrbXaqfwbCpsQa0YI8/w_700/tapestries/standard/~artwork,fw_6500,fh_5525,fy_-488,iw_6500,ih_6500/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-tapestries.jpg",
    s6Tapestry:
      "https://society6.com/product/whale4478346_tapestry?sku=s6-19143535p42a55v412",
    s6WallHanging:
      "https://society6.com/product/whale4478346_wall-hanging?sku=s6-19143535p74a221v771",
    s6WallHangingImage:
      "https://ctl.s6img.com/society6/img/FoysahqriBwpuXCLka6R5p10lKM/w_700/wall-hangings/large/front/~artwork,fw_5678,fh_4058,fy_-810,iw_5678,ih_5678/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-wall-hangings.jpg",
    s6PosterImage:
      "https://ctl.s6img.com/society6/img/ouAAII7941wyMEc_YZx6XwTAdEk/w_700/posters/top/~artwork,fw_2718,fh_3618,fx_-450,iw_3618,ih_3618/s6-original-art-uploads/society6/uploads/misc/e6286186238a4b99a93a77de6e218f1b/~~/whale4478346-posters.jpg",
    s6Poster:
      "https://society6.com/product/whale4478346_poster?sku=s6-19143535p66a213v756",
  },
  {
    title: "Sun Parakeet",
    id: 63,
    keyword: "birds flowers mimosa tree sun parakeet",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas sheet.",
    price: 50,
    image: sunPB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/993195028/sun-parakeet-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Brown Pelican",
    id: 64,
    keyword: "brown birds pelican ocean sea palm trees beach",
    medium: "canvas acrylic",
    size: "9x12 inches.",
    description: "Acrylic paint on canvas.",
    price: 60,
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007085391/brown-pelican-acrylic-painting?ref=shop_home_active_6&frs=1",
    image:
      "https://ctl.s6img.com/society6/img/dEt7UIB3vy5Vn7cXAaFdxeL__yg/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/dEt7UIB3vy5Vn7cXAaFdxeL__yg/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/brown-pelican4805939_stretched-canvas?sku=s6-19709092p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/53Dy_fLp4L4YmKpV_VDFde156AY/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-prints.jpg",
    s6Print:
      "https://society6.com/product/brown-pelican4805939_print?sku=s6-19709092p4a1v45?curator=[Serenity_Images_-_Art_that_Inspires]",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/32TkMXaSXmTfC1CyK07l1P5UyAU/w_700/framed-prints/10x12/conservation-walnut/~artwork/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/brown-pelican4805939_framed-print?sku=s6-19709092p21a12v63a13v54",
    s6TapestryImg:
      "https://ctl.s6img.com/society6/img/srAYl9OgJtFwjWGt-KYeEMM6LeY/w_700/tapestries/standard/~artwork,fw_5525,fh_6500,fy_-552,iw_5525,ih_7604/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-tapestries.jpg",
    s6Tapestry:
      "https://society6.com/product/brown-pelican4805939_tapestry?sku=s6-19709092p42a55v412",
    s6WallHanging:
      "https://society6.com/product/brown-pelican4805939_wall-hanging?sku=s6-19709092p74a221v773",
    s6WallHangingImage:
      "https://ctl.s6img.com/society6/img/cNPpc4kN0p3EAjTJea2UQfx2Nbo/w_700/wall-hangings/large/front/~artwork,fw_4058,fh_5678,fx_-34,iw_4125,ih_5678/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-wall-hangings.jpg",
    s6PosterImage:
      "https://ctl.s6img.com/society6/img/OZN-D5cyV74TT8iipdMYgbowrtE/w_700/posters/top/~artwork,fw_2718,fh_3618,fy_-61,iw_2718,ih_3740/s6-original-art-uploads/society6/uploads/misc/f807536525324542ac741f66519585e4/~~/brown-pelican4805939-posters.jpg",
    s6Poster:
      "https://society6.com/product/brown-pelican4805939_poster?sku=s6-19709092p66a213v983",
  },
  {
    title: "Male Fairy Wren",
    id: 65,
    keyword: "birds sunset sunrise trees leaves splendid fairy wren male",
    medium: "canvas acrylic",
    size: "4x6 inches.",
    description: "Acrylic paint on canvas.",
    price: 50,
    buy: "Not Available",
    etsyListing: null,
    image:
      "https://ctl.s6img.com/society6/img/Xf4RVeSKyq_g6zo1rJKCml1rJpU/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/fb0df57db7be46b59c43c217bb9c3f29/~~/male-splendid-fairy-wren-early-sunset-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/Xf4RVeSKyq_g6zo1rJKCml1rJpU/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/fb0df57db7be46b59c43c217bb9c3f29/~~/male-splendid-fairy-wren-early-sunset-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/male-splendid-fairy-wren-early-sunset_stretched-canvas?sku=s6-19583240p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/exKVEPprScA7lKcLIj26yX6W0zc/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/fb0df57db7be46b59c43c217bb9c3f29/~~/male-splendid-fairy-wren-early-sunset-prints.jpg",
    s6Print:
      "https://society6.com/product/male-splendid-fairy-wren-early-sunset_print?sku=s6-19583240p4a1v45",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/PUwelQzJ1iEq6sgIG6YgLnAFq8Q/w_700/framed-prints/10x12/conservation-walnut/~artwork/s6-original-art-uploads/society6/uploads/misc/fb0df57db7be46b59c43c217bb9c3f29/~~/male-splendid-fairy-wren-early-sunset-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/male-splendid-fairy-wren-early-sunset_framed-print?sku=s6-19583240p21a12v63a13v54",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6TapestryShow: "no",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    s6PosterImage:
      "https://ctl.s6img.com/society6/img/UdfxHBUQ2fHEwHf1Qhj3OYL5l2A/w_700/posters/top/~artwork,fw_2718,fh_3622,fx_-1781,fy_2,iw_5614,ih_3618/s6-original-art-uploads/society6/uploads/misc/fb0df57db7be46b59c43c217bb9c3f29/~~/male-splendid-fairy-wren-early-sunset-posters.jpg",
    s6Poster:
      "https://society6.com/product/male-splendid-fairy-wren-early-sunset_poster?sku=s6-19583240p66a213v756",
  },
  {
    title: "Great Blue Heron",
    id: 69,
    keyword:
      "blue great heron birds landscape lake water lily lilies flowers cattails",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bluheronB,
    s6CanvasShow: "no",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Palm Tree Beach",
    id: 94,
    keyword: "palm tree beach ocean sea water",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: palmbeachB,
    s6CanvasShow: "no",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Snow Owl",
    id: 95,
    keyword: "snow owl cherry plumb tree flowers blossoms bird",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: snowowlB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cannon Ball Flowers",
    id: 4,
    keyword: "flowers cannon tree sky",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas sheet.",
    price: 50,
    image: cannonballflwrsB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007087849/cannon-ball-flowers-acrylic-painting?ref=shop_home_active_3&frs=1",
  },
  {
    title: "Acaia Tree",
    id: 5,
    keyword: "landscape tree acaia africa",
    medium: "canvas sheet acrylic",
    sizes: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas sheet.",
    price: 50,
    image: acaiaB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/993122050/acaia-tree-acrylic-painting?ref=shop_home_active_6&frs=1",
  },
  {
    title: "Celestial Gate",
    id: 6,
    keyword:
      "fantasy landscape sunset night ocean sea water lake celestial gates tori",
    medium: "canvas wrap acrylic",
    size: "small 11 x 14",
    description: "Acrylic paint on 11x14 inch wrapped canvas.",
    price: 70,
    image: celestialB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cherry Blossoms",
    id: 7,
    keyword: "flowers sky flower cherry treeblossom sakura",
    medium: "canvas wrap acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch wrapped canvas.",
    price: 50,
    image: cherryB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Fairy Gate",
    id: 8,
    keyword: "fantasy landscape night sunset tree fairy gate",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: fairyGateB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994184878/fairy-gate-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Dawn Bringer",
    id: 9,
    keyword: "birds night macaw bird sky stars galgaxy gold blue",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: blueMB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007089845/dawn-bringer-blue-macaw-acrylic-painting?ref=shop_home_active_6&frs=1",
  },
  {
    title: "Luna Moth",
    id: 10,
    keyword: "moths night sky tree luna",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: lunaMB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1008148725/luna-moth-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "King Fisher Sunset",
    id: 11,
    keyword: "birds flowers sunset king blossoms cherry pink tree fisher",
    medium: "canvas wrap acrylic",
    size: "medium 11 x 14 ",
    description: "Acrylic paint on 11x14 inch wrapped canvas.",
    price: 70,
    image: kingFB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Loved",
    id: 1,
    keyword: "loved words encouragement saying you",
    medium: "ink paper",
    size: "9x12 inches.",
    description: "Ink on paper.",
    price: 20,
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994182202/you-are-loved-ink-art?ref=shop_home_active_1&frs=1",
    image:
      "https://ctl.s6img.com/society6/img/2nJjr2l5OrS2w1BvZ4hGUz3AhE8/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/2nJjr2l5OrS2w1BvZ4hGUz3AhE8/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/loved4499238_stretched-canvas?sku=s6-19174086p16a6v28",
    s6PrintImg:
      "https://ctl.s6img.com/society6/img/u33LXr5MXWHXxV83-O_lesERKOc/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-prints.jpg",
    s6Print:
      "https://society6.com/product/loved4499238_print?sku=s6-19174086p4a1v45",
    s6FramedImg:
      "https://ctl.s6img.com/society6/img/jbYbVjYfjuljhCn0r9I02KEiRFE/w_700/framed-prints/10x12/scoop-black/~artwork/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-framed-prints.jpg",
    s6Framed:
      "https://society6.com/product/loved4499238_framed-print?sku=s6-19174086p21a12v52a13v54",
    s6TapestryImg:
      "https://ctl.s6img.com/society6/img/yLTKxwGQLFu11lNo9PS0g9PrtBw/w_700/tapestries/standard/~artwork,fw_6500,fh_5525,fx_-552,iw_7604,ih_5525/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-tapestries.jpg",
    s6Tapestry:
      "https://society6.com/product/loved4499238_tapestry?sku=s6-19174086p42a55v412",
    s6WallHanging:
      "https://society6.com/product/loved4499238_wall-hanging?sku=s6-19174086p74a221v771",
    s6WallHangingImage:
      "https://ctl.s6img.com/society6/img/MKWKkKSW-javrjfmom2C1-TzZUU/w_700/wall-hangings/large/front/~artwork,fw_5678,fh_4058,fy_-34,iw_5678,ih_4125/s6-original-art-uploads/society6/uploads/misc/d0108124824b442ea441b05cbd7cb539/~~/loved4499238-wall-hangings.jpg",
    s6PosterShow: "no",
  },
  {
    title: "Jelly Fish",
    id: 13,
    keyword: "jelly fish orange ocean water",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: jellyfB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Magnolias",
    id: 14,
    keyword: "flowers magnolia pink abstract",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas sheet.",
    price: 21,
    image: magsB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Whymsical Tree",
    id: 86,
    keyword: "whymsical tree cherry flowers fantasy abstract",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: fantasytreeB,
    s6CanvasShow: "no",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "King Fisher",
    id: 12,
    keyword: "birds flowers king tree blossoms pink fisher",
    medium: "canvas wrap acrylic",
    size: "medium 11 x 14 ",
    description: "Acrylic paint on 11x14 inch wrapped canvas.",
    price: 70,
    image: kngfB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Owl in Tree",
    id: 15,
    keyword: "owl cherry tree flowers blossoms pink moon night sky stars",
    medium: "canvas acrylic",
    size: "9x12 inches.",
    description: "Acrylic paint on a canvas sheet.",
    price: 60,
    image: owlLightB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Sold",
    etsyListing: null,
  },
  {
    title: "Night Owl",
    id: 32,
    keyword: "birds night owl blue sky tree stars space",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: nightOwlB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1008123127/night-owl-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Magpie Jay",
    id: 33,
    keyword: "magpie jay bird blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: magJayB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Mermaid Cove",
    id: 34,
    keyword: "mermaid sea ocean water fantasy",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: mercoveB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Mermaid Rock",
    id: 35,
    keyword: "magical mermaid rock sun water ocean sea seascape fantasy",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: merRockB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Monarch Butterfly",
    id: 36,
    keyword: "monarch butterfly sky flowers orange",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: monarchB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Amazon Parrots",
    id: 16,
    keyword: "birds parrots green landscape amazon tree",
    medium: "canvas wrap acrylic",
    size: "large 16 x 20 ",
    description: "Acrylic paint on 16x20 inch wrapped canvas.",
    price: 200,
    image: amParrB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cherry Blossoms",
    id: 17,
    keyword: "flowers sky flower cherry tree blossom sakura",
    medium: "canvas wrap acrylic",
    size: "small 8 x 10",
    description: "Acrylic paint on 8x10 inch canvas pannel.",
    price: 50,
    image: cherry2B,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Blue Jay Almond Blossoms",
    id: 18,
    keyword: "birds jay blue almond blossoms flowers tree",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 250,
    image: blueJayB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Chickadee on Cherry Tree",
    id: 19,
    keyword: "birds cherry blossoms flowers tree chickadee",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 250,
    image: chickadeeB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cresting Wave",
    id: 20,
    keyword: "ocean seascape water wave blue abstract pour",
    medium: "canvas acrylic",
    size: "medium",
    description: "Acrylic paint on canvas.",
    price: 60,
    image: crWaveB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Deer at Night",
    id: 21,
    keyword: "night deer blue sky purple moon stars space",
    medium: "canvas sheet acrylic",
    size: "small",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: deernightB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Flowering Orange Tree",
    id: 22,
    keyword: "flowers blossoms tree orange",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: orangesB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Gold Fish",
    id: 23,
    keyword: "gold fish orange water lilly",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: goldfishB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Calm Blue",
    id: 24,
    keyword: "ocean seascape water sky blue abstract",
    medium: "canvas acrylic",
    size: "medium 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas sheet.",
    price: 60,
    image: calmB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/993124780/calm-blue-acrylic-painting?ref=shop_home_active_8&frs=1",
  },
  {
    title: "Hidden Hummingbird",
    id: 25,
    keyword: "hidden humming bird abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: hidhumB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Hummingbird Morning Glories",
    id: 26,
    keyword: "humming  bird morning glories flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: humbmrnB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Crane over Mt. Fuji",
    id: 27,
    keyword: "japanese crane bird cherry blossoms mountain mt fuji flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: cranefujiB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1008095715/japanese-crane-over-mt-fuji-acrylic?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Love Bleeds",
    id: 28,
    keyword: "bleeding heart love flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bldngHrtB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Healed and Whole",
    id: 29,
    keyword: "flower say purple words",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: healedB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Rise and Shine",
    id: 106,
    keyword: "rise and shine morning glory flower blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: riseB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Thorns",
    id: 30,
    keyword: "thorns every words say roses flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: thornsB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Magical Summer",
    id: 31,
    keyword: "magical summer flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: magSummB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1008011487/magical-summer-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Barn Owl",
    id: 38,
    keyword: "flowers blossoms cherry owl bird night",
    medium: "canvas acrylic",
    size: "",
    description: ".",
    price: 21,
    image: owlchB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Night Hill",
    id: 39,
    keyword: "night sky ocean sea water landscape",
    medium: "canvas acrylic",
    size: " ",
    description: "Acrylic paint on canvas.",
    price: 20,
    image: nightHillB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994042128/night-hill-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Ocean Dragon",
    id: 40,
    keyword: "water ocean sea dragon fantasy cute blue",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: ocDragB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1008001697/water-dragon-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Oriole",
    id: 41,
    keyword: "flowers sky flower almond blossoms bird oriole",
    medium: "canvas wrap acrylic",
    size: "small 8 x 10",
    description: "Acrylic paint on 8x10 inch canvas pannel.",
    price: 50,
    image: orioleLongB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Pair of Luna Moths",
    id: 42,
    keyword: "lunar moths insect bug sky blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 60,
    image: pairMothsB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Peacock Feather",
    id: 43,
    keyword: "birds peacock blue feather",
    medium: "canvas sheet acrylic",
    size: "small 9 x 12",
    description: "Acrylic paint on 9x12 inch canvas paper.",
    price: 50,
    image: pFeathersB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994036318/peacock-feather-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Pink Flowers",
    id: 44,
    keyword: "cherry blossoms pink flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 25,
    image: pFloB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Enjoy the Simple Things",
    id: 45,
    keyword: "plumb cherry blossoms flowers simple enjoy",
    medium: "canvas acrylic",
    size: "medium",
    description: "Acrylic paint on canvas.",
    price: 60,
    image: simpleB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994033578/simple-things-plumb-blossom-acrylic?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Tsubaki",
    id: 46,
    keyword: "japanese camellia tsubaki flowers blossoms pink",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: tsubakiB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Shine",
    id: 47,
    keyword: "desert rose flowers shine",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 250,
    image: deRoseB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007129067/desert-rose-acrylic-painting?ref=shop_home_active_5&frs=1",
  },
  {
    title: "Solitary Beauty",
    id: 48,
    keyword: "water lily flowers pink water",
    medium: "canvas sheet acrylic",
    size: "small",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: soliB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sun Dragon",
    id: 49,
    keyword: "sun shine dragon cherry tree blossoms fantasy flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: sunDraB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Wings of Night",
    id: 50,
    keyword: "birds owl night sunset sky wings",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: null,
    image: wingsNightB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Star Fall",
    id: 51,
    keyword: "stars fall abstract pour blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: starFallB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "The Wren",
    id: 52,
    keyword: "wren birds flowers cherry blossoms pink bird",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: wrenB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "The Glory of Morning",
    id: 53,
    keyword: "morning glories flowers night sky space stars blue dawn",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: morningGloryB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007983937/glory-of-morning-morning-glories-acrylic?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Winter's End",
    id: 54,
    keyword: "magical winter spring grey flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: winterEndB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/992896520/winters-end-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Pair of Peacocks",
    id: 66,
    keyword: "birds peacocks pair",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: pairpeacocksB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Birth of an Island",
    id: 67,
    keyword: "birth island abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: islandB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cosmic Waters",
    id: 76,
    keyword: "abstract pour water cosmic",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: coswatB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sunset Waves",
    id: 70,
    keyword: "sunset waves water abstract pour blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: brightabB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Golden Blues",
    id: 92,
    keyword: "gold blue abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: gbluB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Bubbling River",
    id: 71,
    keyword: "bubbles bubbling river water abstract pour blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bubblingB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Fire Edge Nebula",
    id: 88,
    keyword: "fire edge nebula space abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: firenebB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Nebula",
    id: 85,
    keyword: "blue nebula space abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bluenebulaB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Giant Turtle",
    id: 72,
    keyword: "giant turtle sea ocean water",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: giantturtleB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Gladiolus",
    id: 73,
    keyword: "gladiolus flowers pink",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: gladiB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Lake Side",
    id: 74,
    keyword: "lake side swamp water abstract",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: lakesideB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/994019502/lake-side-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  {
    title: "Wisteria",
    id: 75,
    keyword: "wisteria flowers plant purple",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: wisteriaB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Blue Butterfly",
    id: 68,
    keyword: "blue butterfly flowers insect",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: blubutterflyB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Long Tailed Titt",
    id: 77,
    keyword: "long tail birds titt",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: titB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Texas Seascape",
    id: 78,
    keyword: "texas seascape ocean palm trees water",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: texasB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Swallowtail Butterfly",
    id: 79,
    keyword: "swallowtail butterfly purple flowers insect",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: swallbutrflyB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sunset Roses",
    id: 80,
    keyword: "sunset roses flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: sunsroseB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sea Turtle",
    id: 81,
    keyword: "sea turtle reef ocean water",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: seaturtleB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sand Pipers",
    id: 83,
    keyword: "sand pipers birds beach ocean water sea",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: spiperB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Cardinal and Dogwood",
    id: 87,
    keyword: "cardinal dogwood tree flowers pink snow",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: cardinalB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Giraffes",
    id: 89,
    keyword: "giraffes baby africa plains tree acia",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image:
      "https://ctl.s6img.com/society6/img/9hhbrTJ0OcO53MpdxuWY73mrI84/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/53bef88059a9447e99146fb252826f12/~~/giraffe2132847-canvas.jpg",
    s6CanvasPrintImg:
      "https://ctl.s6img.com/society6/img/9hhbrTJ0OcO53MpdxuWY73mrI84/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/53bef88059a9447e99146fb252826f12/~~/giraffe2132847-canvas.jpg",
    s6CanvasPrint:
      "https://society6.com/product/giraffe2132847_stretched-canvas?sku=s6-11131320p16a6v28",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Gerainums",
    id: 90,
    keyword: "gerainums red flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: gerB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Giant Panda",
    id: 91,
    keyword: "giant panda black white",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: bwpandaB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Morning Glories",
    id: 93,
    keyword: "morning glories flowers blue",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: mornB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Pink Aqua",
    id: 96,
    keyword: "pink aqua abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: pinkaquaB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sea Foam",
    id: 97,
    keyword: "sea foam ocean water abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: seafoamB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sun Fire",
    id: 98,
    keyword: "sun fire abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: sunfireB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Solar Flare",
    id: 99,
    keyword: "solar flare abstract pour",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: solarflareB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Pink Flowers",
    id: 100,
    keyword: "pink flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: pflwrB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Plumeria",
    id: 101,
    keyword: "plumeria flowers pink",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: plumB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Purselane",
    id: 102,
    keyword: "purselane pink flowers",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: purB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Sea Turtle",
    id: 103,
    keyword: "sea turtle ocean",
    medium: "canvas acrylic",
    size: "",
    description: "Acrylic paint on canvas.",
    price: 50,
    image: seatB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "The Stuff of Life",
    id: 104,
    keyword: "stuff the life abstract",
    medium: "Acrylic paint on canvas.",
    size: "",
    description: "",
    price: 50,
    image:
      "https://ctl.s6img.com/society6/img/m6rb3oQbJs0z6iC_AhmWWnOY1bk/w_700/canvas/~artwork/s6-original-art-uploads/society6/uploads/misc/68387be39ffb45198a36cfc4072d9b7b/~~/the-stuff-of-life-canvas.jpg",
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Not Available",
    etsyListing: null,
  },
  {
    title: "Enchanted Spring",
    id: 105,
    keyword: "enchanted spring tree cherry blossoms flowers pink",
    medium: "Acrylic paint on canvas.",
    size: "",
    description: "",
    price: 50,
    image: enchantB,
    s6CanvasPrintImg: "",
    s6CanvasPrint: "",
    s6PrintImg: "",
    s6Print: "",
    s6FramedImg: "",
    s6Framed: "",
    s6TapestryImg: "",
    s6Tapestry: "",
    s6WallHanging: "",
    s6WallHangingImage: "",
    s6WallHangingShow: "no",
    buy: "Buy Now!",
    etsyListing:
      "https://www.etsy.com/listing/1007635893/enchanted-spring-acrylic-painting?ref=shop_home_active_1&frs=1",
  },
  // {
  //   title: "",
  //   id: 107,
  //   keyword: "",
  //   medium: "canvas acrylic",
  //   size: "",
  //   description: "Acrylic paint on canvas.",
  //   price: 50,
  //   image: null,
  //   s6CanvasPrintImg: "",
  //   s6CanvasPrint: "",
  //   s6PrintImg: "",
  //   s6Print: "",
  //   s6FramedImg: "",
  //   s6Framed: "",
  //   s6TapestryImg: "",
  //   s6Tapestry: "",
  //   s6WallHanging: "",
  //   s6WallHangingImage: "",
  //   s6WallHangingShow: "no",
  //   buy: "Not Available",
  //   etsyListing: null,
  // },
  // {
  //   title: "",
  //   id: 108,
  //   keyword: "",
  //   medium: "canvas acrylic",
  //   size: "",
  //   description: "Acrylic paint on canvas.",
  //   price: 50,
  //   image: null,
  //   s6CanvasPrintImg: "",
  //   s6CanvasPrint: "",
  //   s6PrintImg: "",
  //   s6Print: "",
  //   s6FramedImg: "",
  //   s6Framed: "",
  //   s6TapestryImg: "",
  //   s6Tapestry: "",
  // s6WallHanging: "",
  //   s6WallHangingImage: "",
  //   s6WallHangingShow: "no",
  //   buy: "Not Available",
  //   etsyListing: null,
  // },
  // {
  //   title: "",
  //   id: 109,
  //   keyword: "",
  //   medium: "canvas acrylic",
  //   size: "",
  //   description: "Acrylic paint on canvas.",
  //   price: 50,
  //   image: null,
  //   s6CanvasPrintImg: "",
  //   s6CanvasPrint: "",
  //   s6PrintImg: "",
  //   s6Print: "",
  //   s6FramedImg: "",
  //   s6Framed: "",
  //   s6TapestryImg: "",
  //   s6Tapestry: "",
  // s6WallHanging: "",
  //   s6WallHangingImage: "",
  //   s6WallHangingShow: "no",
  //   buy: "Not Available",
  //   etsyListing: null,
  // },
  // {
  //   title: "",
  //   id: 110,
  //   keyword: "",
  //   medium: "canvas acrylic",
  //   size: "",
  //   description: "Acrylic paint on canvas.",
  //   price: 50,
  //   image: null,
  // s6CanvasPrintImg: "",
  // s6CanvasPrint: "",
  // s6PrintImg: "",
  // s6Print: "",
  // s6FramedImg: "",
  // s6Framed: "",
  // s6TapestryImg: "",
  // s6Tapestry: "",
  // s6WallHanging: "",
  //   s6WallHangingImage: "",
  //   s6WallHangingShow: "no",
  // buy: "Not Available",
  // etsyListing: null,
  // },
];

export default GalleryArray;
